[tool.poetry]
name = "gomoku"
version = "0.1.0"
description = ""
authors = ["ivan-karaberov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
