# Board
EMPTY = 0
WHITE = 1
BLACK = -1
BOARD_SIZE = 15
LINE_FOR_WIN = 5
PLAYER_COLOR = BLACK

# Window
TITLE = "Gomoku"
WINDOW_SIZE = 500
WHITE_COLOR = "white"
BLACK_COLOR = "black"
CELL_COLOR_DEFAULT = "grey"
CELL_HOVER_COLOR = "#d3d3d3"
WINDOWS_COLOR_DEFAULT = "white"
